### ISSUE TITLE
support string in LoadRawData()

### ISSUE THREAD

**Issue by kjellkvinge** [montanaflynn/stats#67]
Thank you for this great package. 
I added support for a string and io.Reader in LoadRawData() so it support whitespace separated strings.

i.e
```go
stats.LoadRawData("1.1 2 3.0 4 5")

// or
stats.LoadRawData(os.Stdin)

```

Is this something you would consider implemented in you package? If so, I can create a pull request.

kk

**Comment by montanaflynn** [comment]
How about as a new function? `LoadRawDataString`?

**Comment by montanaflynn** [comment]
Actually looking at the function signature for `LoadRawData` we can just add support for a single string or io.reader without breaking backward compatibility since it accepts an `interface{}` arg so I'd welcome a PR!

Also this should be possible now with just, right?

`stats.LoadRawData(strings.Split("1.1 2 3.0 4 5", " "))`

**Comment by kjellkvinge** [comment]
yes, that signature accept everything, but I`ll guess you will have to draw the line somewhere 😄 

I`ll make a PR.

**Comment by montanaflynn** [comment]
Thanks @kjellkvinge, I merged your PR!
